import { appendFileSync, mkdirSync, readFileSync } from 'node:fs'
import { randomUUID } from 'node:crypto'
import { dirname } from 'node:path'
import type {
  DistanceAssessment,
  Issue,
  IssueActionRequest,
  IssueActionResult,
  IssueMilestone,
  IssueSnapshot,
  Plan,
  Sprint,
  SprintState,
} from '../shared/types'

/// The Mastermind substrate's disk + memory side. Main is the single arbiter:
/// every mutation funnels through `apply`, which runs synchronously to completion
/// in one event-loop tick — so writes never interleave and an atomic claim is a
/// plain check-then-append. State is an append-only JSONL event log
/// (`SPINE_DIR/issues.jsonl`) materialized in memory: `load` replays the log,
/// `apply` reduces + appends one durable line + emits. No debounce (unlike the
/// workspace's drag-stream) — issue actions are deliberate events. Everything is
/// per-project (per canvas): each canvas has its own vision, sprints, and issues.

/// Replay determinism: a create action generates ids and stamps timestamps at
/// apply time, so those must be the SAME on replay or later refs (a plan's
/// `sprintRef`, an issue's `planRef`) would dangle. We persist the generated ids
/// and the timestamp in each log entry and feed them back through this context on
/// replay — apply pulls fresh ones, replay reads the recorded ones, same order.
interface ApplyCtx {
  id(): string
  now(): number
}

interface LogEntry {
  seq: number
  ts: number
  /** Ids generated by this action, in reduce-call order (replay feeds them back). */
  ids: string[]
  action: IssueActionRequest
}

/// Legal sprint-state advances for `sprint.setState` (the manual gates in v1; the
/// same transitions an auditor verdict drives later). Forward, plus one step back
/// for human correction. DONE is terminal; REALIGNMENT_PENDING is left ONLY via
/// `sprint.resolveRealignment`. Store-internal advances (plan.create →
/// PLAN_REVIEW, plan.approve → APPROVED, first issue.create → DECOMPOSED) are
/// known-legal and set directly.
const SPRINT_TRANSITIONS: Record<SprintState, SprintState[]> = {
  DRAFT: ['PLAN_REVIEW'],
  PLAN_REVIEW: ['APPROVED', 'DRAFT'],
  APPROVED: ['DECOMPOSED', 'PLAN_REVIEW'],
  DECOMPOSED: ['EXECUTING', 'APPROVED'],
  EXECUTING: ['OUTCOME_REVIEW', 'DECOMPOSED'],
  OUTCOME_REVIEW: ['DONE', 'EXECUTING'],
  DONE: [],
  REALIGNMENT_PENDING: [],
}

const empty = (): IssueSnapshot => ({
  visions: [],
  versions: [],
  sprints: [],
  plans: [],
  issues: [],
  distance: [],
})

const ok = (id?: string): IssueActionResult => ({ ok: true, id })
const fail = (message: string): IssueActionResult => ({ ok: false, message })

export class IssueStore {
  /** Re-pushed in whole on every applied action (cf. spine.onUpdate → card-event). */
  onChange?: (snapshot: IssueSnapshot) => void
  /** A meaningful transition fired (e.g. a plan was approved) — the mastermind's
   *  wake signal. NOT fired during replay (load), only on live applies. */
  onMilestone?: (m: IssueMilestone) => void

  private state: IssueSnapshot = empty()
  private seq = 0
  /** True while replaying the log in load() — suppresses milestone emission so a
   *  restart doesn't re-fire "plan ready" and re-spawn leads. */
  private replaying = false

  constructor(private file: string) {}

  /** Replay the log into memory. Sync — call before the first `load-issue-store`
   *  is served. Tolerates a malformed line (skip + warn), like WorkspaceStore. */
  load(): void {
    this.state = empty()
    this.seq = 0
    let raw: string
    try {
      raw = readFileSync(this.file, 'utf8')
    } catch {
      return // first run / unreadable → empty store
    }
    this.replaying = true
    try {
      for (const line of raw.split('\n')) {
        if (!line.trim()) continue
        let entry: LogEntry
        try {
          entry = JSON.parse(line) as LogEntry
        } catch {
          console.warn('[issues] skipping unparseable log line')
          continue
        }
        let cursor = 0
        const ctx: ApplyCtx = { id: () => entry.ids[cursor++] ?? randomUUID(), now: () => entry.ts }
        const result = this.reduce(entry.action, ctx)
        if (!result.ok) console.warn('[issues] replay rejected an action:', result.message)
        if (typeof entry.seq === 'number') this.seq = Math.max(this.seq, entry.seq)
      }
    } finally {
      this.replaying = false
    }
  }

  /** Emit a milestone (the mastermind's wake signal) — suppressed during replay. */
  private milestone(m: IssueMilestone): void {
    if (!this.replaying) this.onMilestone?.(m)
  }

  snapshot(): IssueSnapshot {
    return this.state
  }

  /** Validate → reduce → append one durable line → emit. The reduce rejects
   *  (without mutating or generating ids) before any state change, so a rejected
   *  action never touches the log. */
  apply(action: IssueActionRequest): IssueActionResult {
    const ts = Date.now()
    const ids: string[] = []
    const ctx: ApplyCtx = {
      id: () => {
        const x = randomUUID()
        ids.push(x)
        return x
      },
      now: () => ts,
    }
    const result = this.reduce(action, ctx)
    if (!result.ok) return result
    const entry: LogEntry = { seq: ++this.seq, ts, ids, action }
    try {
      mkdirSync(dirname(this.file), { recursive: true })
      appendFileSync(this.file, JSON.stringify(entry) + '\n')
    } catch (err) {
      console.error('[issues] append failed', err)
    }
    this.onChange?.(this.state)
    return result
  }

  /** No-op in v1 (each apply is already durable). Seam for future compaction
   *  (write the materialized state as one snapshot line, truncate the log). */
  flush(): void {}

  // The reducer — validates fully BEFORE mutating, so a rejected action leaves
  // state untouched and generates no ids. Shared by apply (live) and load (replay).
  private reduce(action: IssueActionRequest, ctx: ApplyCtx): IssueActionResult {
    const s = this.state
    switch (action.kind) {
      case 'vision.commit': {
        const id = ctx.id()
        const version = {
          id,
          projectId: action.projectId,
          n: s.versions.filter((v) => v.projectId === action.projectId).length + 1,
          body: action.body,
          principles: action.principles,
          antiVision: action.antiVision,
          rationale: action.rationale,
          class: action.class,
          author: 'human' as const,
          committedAt: ctx.now(),
        }
        s.versions.push(version)
        const vision = s.visions.find((v) => v.projectId === action.projectId)
        if (vision) vision.currentVersion = id
        else s.visions.push({ projectId: action.projectId, currentVersion: id })
        this.propagate(action.projectId, id, action.class)
        return ok(id)
      }

      case 'vision.assessDistance': {
        const entry: DistanceAssessment = {
          projectId: action.projectId,
          note: action.note,
          assessedBy: action.assessedBy,
          at: ctx.now(),
        }
        s.distance.push(entry)
        return ok()
      }

      case 'sprint.create': {
        if (!action.projectId) return fail('sprint needs a project')
        const vision = s.visions.find((v) => v.projectId === action.projectId)
        if (!vision?.currentVersion)
          return fail('commit a vision version for this canvas first')
        const id = ctx.id()
        const sprint: Sprint = {
          id,
          projectId: action.projectId,
          visionVersionRef: vision.currentVersion,
          outcome: action.outcome,
          gapRationale: action.gapRationale,
          state: 'DRAFT',
          createdAt: ctx.now(),
        }
        s.sprints.push(sprint)
        return ok(id)
      }

      case 'sprint.setState': {
        const sprint = s.sprints.find((x) => x.id === action.id)
        if (!sprint) return fail('no such sprint')
        if (sprint.state === action.state) return ok(sprint.id)
        if (!SPRINT_TRANSITIONS[sprint.state].includes(action.state))
          return fail(`illegal transition ${sprint.state} → ${action.state}`)
        sprint.state = action.state
        return ok(sprint.id)
      }

      case 'sprint.resolveRealignment': {
        const sprint = s.sprints.find((x) => x.id === action.id)
        if (!sprint) return fail('no such sprint')
        if (sprint.state !== 'REALIGNMENT_PENDING' || !sprint.realignment)
          return fail('sprint is not pending realignment')
        if (action.outcome === 'remove') {
          this.removeSprint(sprint.id)
          return ok()
        }
        // 'aligned' → re-pin to the current version, restore the prior state.
        sprint.visionVersionRef = sprint.realignment.toVisionVersion
        sprint.state = sprint.realignment.priorState
        sprint.realignment = undefined
        return ok(sprint.id)
      }

      case 'sprint.remove': {
        if (!s.sprints.some((x) => x.id === action.id)) return fail('no such sprint')
        this.removeSprint(action.id)
        return ok()
      }

      case 'plan.create': {
        const sprint = s.sprints.find((x) => x.id === action.sprintRef)
        if (!sprint) return fail('no such sprint')
        const id = ctx.id()
        const plan: Plan = {
          id,
          sprintRef: action.sprintRef,
          overview: action.overview,
          stack: action.stack,
          structure: action.structure,
          deps: action.deps,
          nonGoals: action.nonGoals,
          approved: false,
          createdAt: ctx.now(),
        }
        s.plans.push(plan)
        if (sprint.state === 'DRAFT') sprint.state = 'PLAN_REVIEW' // a plan now exists to review
        return ok(id)
      }

      case 'plan.approve': {
        const plan = s.plans.find((x) => x.id === action.id)
        if (!plan) return fail('no such plan')
        plan.approved = true
        const sprint = s.sprints.find((x) => x.id === plan.sprintRef)
        if (sprint && sprint.state === 'PLAN_REVIEW') {
          sprint.state = 'APPROVED' // gate #1
          // "Plan ready" — the cascade trigger the mastermind wakes on.
          this.milestone({
            kind: 'plan-ready',
            projectId: sprint.projectId,
            sprintId: sprint.id,
            detail: sprint.outcome,
          })
        }
        return ok(plan.id)
      }

      case 'issue.create': {
        const plan = s.plans.find((x) => x.id === action.planRef)
        if (!plan) return fail('no such plan')
        const sprint = s.sprints.find((x) => x.id === plan.sprintRef)
        const id = ctx.id()
        const issue: Issue = {
          id,
          planRef: action.planRef,
          title: action.title,
          description: action.description,
          verify: action.verify,
          status: (action.deps?.length ?? 0) > 0 ? 'backlog' : 'ready',
          owner: null,
          phase: action.phase,
          deps: action.deps ?? [],
          labels: action.labels ?? [],
          kind: action.issueKind,
          verdicts: [],
          comments: [],
          intentRef: sprint?.visionVersionRef ?? '',
          createdAt: ctx.now(),
        }
        s.issues.push(issue)
        if (sprint && sprint.state === 'APPROVED') sprint.state = 'DECOMPOSED' // first issue
        return ok(id)
      }

      case 'issue.setStatus': {
        const issue = s.issues.find((x) => x.id === action.id)
        if (!issue) return fail('no such issue')
        issue.status = action.status
        // A worker reaching a terminal state notifies the lead (no polling): done
        // → assign the next frontier / finish the sprint; blocked → unstick it.
        if (action.status === 'done' || action.status === 'blocked') {
          const plan = s.plans.find((p) => p.id === issue.planRef)
          const sprint = plan && s.sprints.find((sp) => sp.id === plan.sprintRef)
          this.milestone({
            kind: action.status === 'done' ? 'issue-done' : 'issue-blocked',
            projectId: sprint?.projectId ?? '',
            issueId: issue.id,
            ownerId: issue.owner ?? undefined,
            detail: issue.title,
          })
        }
        return ok(issue.id)
      }

      case 'issue.claim': {
        const issue = s.issues.find((x) => x.id === action.id)
        if (!issue) return fail('no such issue')
        if (issue.owner) return fail(`already owned by ${issue.owner}`)
        issue.owner = action.owner
        issue.status = 'claimed'
        // The lead assigned this issue to a worker — nudge that worker to start, so
        // the assignment can't be missed if it already checked (the timing race).
        const plan = s.plans.find((p) => p.id === issue.planRef)
        const sprint = plan && s.sprints.find((sp) => sp.id === plan.sprintRef)
        this.milestone({
          kind: 'issue-assigned',
          projectId: sprint?.projectId ?? '',
          issueId: issue.id,
          ownerId: action.owner,
          detail: issue.title,
        })
        return ok(issue.id)
      }

      case 'issue.release': {
        const issue = s.issues.find((x) => x.id === action.id)
        if (!issue) return fail('no such issue')
        issue.owner = null
        if (issue.status === 'claimed' || issue.status === 'in_progress') issue.status = 'ready'
        return ok(issue.id)
      }

      case 'issue.setDeps': {
        const issue = s.issues.find((x) => x.id === action.id)
        if (!issue) return fail('no such issue')
        const known = new Set(s.issues.map((x) => x.id))
        issue.deps = action.deps.filter((d) => d !== issue.id && known.has(d))
        return ok(issue.id)
      }

      case 'issue.postVerdict': {
        const issue = s.issues.find((x) => x.id === action.id)
        if (!issue) return fail('no such issue')
        issue.verdicts.push({
          id: ctx.id(),
          verdict: action.verdict,
          findings: action.findings,
          disposition: action.disposition,
          author: action.author,
          postedAt: ctx.now(),
        })
        return ok(issue.id)
      }

      case 'issue.comment': {
        const issue = s.issues.find((x) => x.id === action.id)
        if (!issue) return fail('no such issue')
        issue.comments.push({
          id: ctx.id(),
          author: action.author,
          body: action.body,
          postedAt: ctx.now(),
        })
        return ok(issue.id)
      }

      default:
        return fail(`unknown action: ${(action as { kind: string }).kind}`)
    }
  }

  /** The propagation pass: a canvas's vision bump re-runs gate #0 across THAT
   *  canvas's sprints. A clarification invalidates nothing; a redirection /
   *  expansion moves every non-terminal sprint pinned to an older version into
   *  REALIGNMENT_PENDING for a human (later: auditor) to re-verdict via
   *  `sprint.resolveRealignment`. */
  private propagate(projectId: string, newVersionId: string, cls: string): void {
    if (cls === 'clarification') return
    for (const sprint of this.state.sprints) {
      if (sprint.projectId !== projectId) continue
      if (sprint.state === 'DONE' || sprint.state === 'REALIGNMENT_PENDING') continue
      if (sprint.visionVersionRef === newVersionId) continue
      sprint.realignment = {
        fromVisionVersion: sprint.visionVersionRef,
        toVisionVersion: newVersionId,
        priorState: sprint.state,
      }
      sprint.state = 'REALIGNMENT_PENDING'
    }
  }

  private removeSprint(sprintId: string): void {
    const planIds = new Set(
      this.state.plans.filter((p) => p.sprintRef === sprintId).map((p) => p.id),
    )
    this.state.issues = this.state.issues.filter((i) => !planIds.has(i.planRef))
    this.state.plans = this.state.plans.filter((p) => p.sprintRef !== sprintId)
    this.state.sprints = this.state.sprints.filter((sp) => sp.id !== sprintId)
  }
}
