import { appendFileSync, mkdirSync, readFileSync } from 'node:fs'
import { randomUUID } from 'node:crypto'
import { dirname } from 'node:path'
import type {
  Conception,
  DistanceAssessment,
  Idea,
  Issue,
  IssueActionRequest,
  IssueActionResult,
  IssueMilestone,
  IssueSnapshot,
  Plan,
  Sprint,
  SprintState,
} from '../shared/types'

/// The Mastermind substrate's disk + memory side. Main is the single arbiter:
/// every mutation funnels through `apply`, which runs synchronously to completion
/// in one event-loop tick — so writes never interleave and an atomic claim is a
/// plain check-then-append. State is an append-only JSONL event log
/// (`SPINE_DIR/issues.jsonl`) materialized in memory: `load` replays the log,
/// `apply` reduces + appends one durable line + emits. No debounce (unlike the
/// workspace's drag-stream) — issue actions are deliberate events. Everything is
/// per-project (per canvas): each canvas has its own vision, sprints, and issues.

/// Replay determinism: a create action generates ids and stamps timestamps at
/// apply time, so those must be the SAME on replay or later refs (a plan's
/// `sprintRef`, an issue's `planRef`) would dangle. We persist the generated ids
/// and the timestamp in each log entry and feed them back through this context on
/// replay — apply pulls fresh ones, replay reads the recorded ones, same order.
interface ApplyCtx {
  id(): string
  now(): number
}

interface LogEntry {
  seq: number
  ts: number
  /** Ids generated by this action, in reduce-call order (replay feeds them back). */
  ids: string[]
  action: IssueActionRequest
}

/// Legal sprint-state advances for `sprint.setState` (the manual gates in v1; the
/// same transitions an auditor verdict drives later). Forward, plus one step back
/// for human correction. DONE is terminal; REALIGNMENT_PENDING is left ONLY via
/// `sprint.resolveRealignment`. Store-internal advances (plan.create →
/// PLAN_REVIEW, plan.approve → APPROVED, first issue.create → DECOMPOSED) are
/// known-legal and set directly.
const SPRINT_TRANSITIONS: Record<SprintState, SprintState[]> = {
  DRAFT: ['PLAN_REVIEW'],
  PLAN_REVIEW: ['APPROVED', 'DRAFT'],
  APPROVED: ['DECOMPOSED', 'PLAN_REVIEW'],
  DECOMPOSED: ['EXECUTING', 'APPROVED'],
  EXECUTING: ['OUTCOME_REVIEW', 'DECOMPOSED'],
  OUTCOME_REVIEW: ['DONE', 'EXECUTING'],
  DONE: [],
  REALIGNMENT_PENDING: [],
}

const empty = (): IssueSnapshot => ({
  visions: [],
  versions: [],
  sprints: [],
  plans: [],
  issues: [],
  distance: [],
  conceptions: [],
})

const ok = (id?: string): IssueActionResult => ({ ok: true, id })
const fail = (message: string): IssueActionResult => ({ ok: false, message })

export class IssueStore {
  /** Re-pushed in whole on every applied action (cf. spine.onUpdate → card-event). */
  onChange?: (snapshot: IssueSnapshot) => void
  /** A meaningful transition fired (e.g. a plan was approved) — the mastermind's
   *  wake signal. NOT fired during replay (load), only on live applies. */
  onMilestone?: (m: IssueMilestone) => void

  private state: IssueSnapshot = empty()
  private seq = 0
  /** True while replaying the log in load() — suppresses milestone emission so a
   *  restart doesn't re-fire "plan ready" and re-spawn leads. */
  private replaying = false

  constructor(private file: string) {}

  /** Replay the log into memory. Sync — call before the first `load-issue-store`
   *  is served. Tolerates a malformed line (skip + warn), like WorkspaceStore. */
  load(): void {
    this.state = empty()
    this.seq = 0
    let raw: string
    try {
      raw = readFileSync(this.file, 'utf8')
    } catch {
      return // first run / unreadable → empty store
    }
    this.replaying = true
    try {
      for (const line of raw.split('\n')) {
        if (!line.trim()) continue
        let entry: LogEntry
        try {
          entry = JSON.parse(line) as LogEntry
        } catch {
          console.warn('[issues] skipping unparseable log line')
          continue
        }
        let cursor = 0
        const ctx: ApplyCtx = { id: () => entry.ids[cursor++] ?? randomUUID(), now: () => entry.ts }
        const result = this.reduce(entry.action, ctx)
        if (!result.ok) console.warn('[issues] replay rejected an action:', result.message)
        if (typeof entry.seq === 'number') this.seq = Math.max(this.seq, entry.seq)
      }
    } finally {
      this.replaying = false
    }
  }

  /** Emit a milestone (the mastermind's wake signal) — suppressed during replay. */
  private milestone(m: IssueMilestone): void {
    if (!this.replaying) this.onMilestone?.(m)
  }

  snapshot(): IssueSnapshot {
    return this.state
  }

  /** Validate → reduce → append one durable line → emit. The reduce rejects
   *  (without mutating or generating ids) before any state change, so a rejected
   *  action never touches the log. */
  apply(action: IssueActionRequest): IssueActionResult {
    const ts = Date.now()
    const ids: string[] = []
    const ctx: ApplyCtx = {
      id: () => {
        const x = randomUUID()
        ids.push(x)
        return x
      },
      now: () => ts,
    }
    const result = this.reduce(action, ctx)
    if (!result.ok) return result
    const entry: LogEntry = { seq: ++this.seq, ts, ids, action }
    try {
      mkdirSync(dirname(this.file), { recursive: true })
      appendFileSync(this.file, JSON.stringify(entry) + '\n')
    } catch (err) {
      console.error('[issues] append failed', err)
    }
    this.onChange?.(this.state)
    return result
  }

  /** No-op in v1 (each apply is already durable — nothing is buffered). Seam for future
   *  compaction (write the materialized state as one snapshot line, truncate the log).
   *  Named `compact`, not `flush`: cf. WorkspaceStore.flush, a real write-or-lose-data on
   *  quit; this store has nothing to flush. */
  compact(): void {}

  // The reducer — validates fully BEFORE mutating, so a rejected action leaves
  // state untouched and generates no ids. Shared by apply (live) and load (replay).
  private reduce(action: IssueActionRequest, ctx: ApplyCtx): IssueActionResult {
    const s = this.state
    switch (action.kind) {
      case 'vision.commit': {
        const id = ctx.id()
        const version = {
          id,
          projectId: action.projectId,
          n: s.versions.filter((v) => v.projectId === action.projectId).length + 1,
          body: action.body,
          principles: action.principles,
          antiVision: action.antiVision,
          rationale: action.rationale,
          class: action.class,
          author: 'human' as const,
          committedAt: ctx.now(),
        }
        s.versions.push(version)
        const vision = s.visions.find((v) => v.projectId === action.projectId)
        if (vision) vision.currentVersion = id
        else s.visions.push({ projectId: action.projectId, currentVersion: id })
        this.propagate(action.projectId, id, action.class)
        return ok(id)
      }

      case 'vision.assessDistance': {
        const entry: DistanceAssessment = {
          projectId: action.projectId,
          note: action.note,
          assessedBy: action.assessedBy,
          at: ctx.now(),
        }
        s.distance.push(entry)
        return ok()
      }

      case 'sprint.create': {
        if (!action.projectId) return fail('sprint needs a project')
        const vision = s.visions.find((v) => v.projectId === action.projectId)
        if (!vision?.currentVersion)
          return fail('commit a vision version for this canvas first')
        const id = ctx.id()
        const sprint: Sprint = {
          id,
          projectId: action.projectId,
          visionVersionRef: vision.currentVersion,
          title: action.title ?? '',
          outcome: action.outcome,
          gapRationale: action.gapRationale,
          state: 'DRAFT',
          createdAt: ctx.now(),
        }
        s.sprints.push(sprint)
        return ok(id)
      }

      case 'sprint.setState': {
        const sprint = s.sprints.find((x) => x.id === action.id)
        if (!sprint) return fail('no such sprint')
        if (sprint.state === action.state) return ok(sprint.id)
        if (!SPRINT_TRANSITIONS[sprint.state].includes(action.state))
          return fail(`illegal transition ${sprint.state} → ${action.state}`)
        sprint.state = action.state
        if (action.state === 'DONE') {
          // The sprint's outcome was verified — the autonomous loop's "find the
          // next" trigger (the mastermind runs the off-card idea tournament here).
          this.milestone({
            kind: 'outcome-verified',
            projectId: sprint.projectId,
            sprintId: sprint.id,
            detail: sprint.title || sprint.outcome,
          })
        }
        return ok(sprint.id)
      }

      case 'sprint.resolveRealignment': {
        const sprint = s.sprints.find((x) => x.id === action.id)
        if (!sprint) return fail('no such sprint')
        if (sprint.state !== 'REALIGNMENT_PENDING' || !sprint.realignment)
          return fail('sprint is not pending realignment')
        if (action.outcome === 'remove') {
          this.removeSprint(sprint.id)
          return ok()
        }
        // 'aligned' → re-pin to the current version, restore the prior state.
        sprint.visionVersionRef = sprint.realignment.toVisionVersion
        sprint.state = sprint.realignment.priorState
        sprint.realignment = undefined
        return ok(sprint.id)
      }

      case 'sprint.remove': {
        if (!s.sprints.some((x) => x.id === action.id)) return fail('no such sprint')
        this.removeSprint(action.id)
        return ok()
      }

      case 'plan.create': {
        const sprint = s.sprints.find((x) => x.id === action.sprintRef)
        if (!sprint) return fail('no such sprint')
        const id = ctx.id()
        const plan: Plan = {
          id,
          sprintRef: action.sprintRef,
          overview: action.overview,
          stack: action.stack,
          structure: action.structure,
          deps: action.deps,
          nonGoals: action.nonGoals,
          approved: false,
          createdAt: ctx.now(),
        }
        s.plans.push(plan)
        if (sprint.state === 'DRAFT') sprint.state = 'PLAN_REVIEW' // a plan now exists to review
        return ok(id)
      }

      case 'plan.approve': {
        const plan = s.plans.find((x) => x.id === action.id)
        if (!plan) return fail('no such plan')
        plan.approved = true
        const sprint = s.sprints.find((x) => x.id === plan.sprintRef)
        if (sprint && sprint.state === 'PLAN_REVIEW') {
          sprint.state = 'APPROVED' // gate #1
          // "Plan ready" — the cascade trigger the mastermind wakes on.
          this.milestone({
            kind: 'plan-ready',
            projectId: sprint.projectId,
            sprintId: sprint.id,
            detail: sprint.title || sprint.outcome,
          })
        }
        return ok(plan.id)
      }

      case 'issue.create': {
        const plan = s.plans.find((x) => x.id === action.planRef)
        if (!plan) return fail('no such plan')
        const sprint = s.sprints.find((x) => x.id === plan.sprintRef)
        const id = ctx.id()
        const issue: Issue = {
          id,
          planRef: action.planRef,
          title: action.title,
          description: action.description,
          verify: action.verify,
          status: (action.deps?.length ?? 0) > 0 ? 'backlog' : 'ready',
          owner: null,
          phase: action.phase,
          deps: action.deps ?? [],
          labels: action.labels ?? [],
          kind: action.issueKind,
          verdicts: [],
          comments: [],
          intentRef: sprint?.visionVersionRef ?? '',
          createdAt: ctx.now(),
        }
        s.issues.push(issue)
        if (sprint && sprint.state === 'APPROVED') sprint.state = 'DECOMPOSED' // first issue
        return ok(id)
      }

      case 'issue.setStatus': {
        const issue = s.issues.find((x) => x.id === action.id)
        if (!issue) return fail('no such issue')
        issue.status = action.status
        issue.stalledAt = undefined // a status report is proof of life — clear any stall latch
        // A worker reaching a terminal state notifies the lead (no polling): done
        // → assign the next frontier / finish the sprint; blocked → unstick it.
        if (action.status === 'done' || action.status === 'blocked') {
          const plan = s.plans.find((p) => p.id === issue.planRef)
          const sprint = plan && s.sprints.find((sp) => sp.id === plan.sprintRef)
          this.milestone({
            kind: action.status === 'done' ? 'issue-done' : 'issue-blocked',
            projectId: sprint?.projectId ?? '',
            issueId: issue.id,
            ownerId: issue.owner ?? undefined,
            detail: issue.title,
          })
        }
        return ok(issue.id)
      }

      case 'issue.claim': {
        const issue = s.issues.find((x) => x.id === action.id)
        if (!issue) return fail('no such issue')
        if (issue.owner) return fail(`already owned by ${issue.owner}`)
        issue.owner = action.owner
        issue.status = 'claimed'
        issue.stalledAt = undefined // fresh claim — re-arm the stall latch
        // The lead assigned this issue to a worker — nudge that worker to start, so
        // the assignment can't be missed if it already checked (the timing race).
        const plan = s.plans.find((p) => p.id === issue.planRef)
        const sprint = plan && s.sprints.find((sp) => sp.id === plan.sprintRef)
        this.milestone({
          kind: 'issue-assigned',
          projectId: sprint?.projectId ?? '',
          issueId: issue.id,
          ownerId: action.owner,
          detail: issue.title,
        })
        return ok(issue.id)
      }

      case 'issue.release': {
        const issue = s.issues.find((x) => x.id === action.id)
        if (!issue) return fail('no such issue')
        issue.owner = null
        issue.stalledAt = undefined // no owner — no lease, no stall latch
        if (issue.status === 'claimed' || issue.status === 'in_progress') issue.status = 'ready'
        return ok(issue.id)
      }

      case 'issue.setStall': {
        // Main-process stall sweep only (not agent-facing). Edge-triggered: fire the
        // `stalled` milestone once on the not-stalled → stalled transition; clear the
        // latch when the owner shows life. Idempotent, so a re-applied edge is a no-op.
        const issue = s.issues.find((x) => x.id === action.id)
        if (!issue) return fail('no such issue')
        const wasStalled = issue.stalledAt != null
        if (action.stalled && !wasStalled) {
          if (!issue.owner) return fail('cannot stall an unowned issue')
          if (issue.status === 'done' || issue.status === 'superseded')
            return fail(`cannot stall a ${issue.status} issue`)
          issue.stalledAt = ctx.now()
          const plan = s.plans.find((p) => p.id === issue.planRef)
          const sprint = plan && s.sprints.find((sp) => sp.id === plan.sprintRef)
          this.milestone({
            kind: 'stalled',
            projectId: sprint?.projectId ?? '',
            sprintId: sprint?.id,
            issueId: issue.id,
            ownerId: issue.owner ?? undefined,
            detail: issue.title,
          })
        } else if (!action.stalled && wasStalled) {
          issue.stalledAt = undefined
        }
        return ok(issue.id)
      }

      case 'issue.setDeps': {
        const issue = s.issues.find((x) => x.id === action.id)
        if (!issue) return fail('no such issue')
        // A retired (superseded) issue is never `done`, so depending on it would
        // deadlock the dependent forever — drop those alongside unknown / self refs.
        const live = new Set(s.issues.filter((x) => x.status !== 'superseded').map((x) => x.id))
        issue.deps = action.deps.filter((d) => d !== issue.id && live.has(d))
        return ok(issue.id)
      }

      case 'issue.postVerdict': {
        const issue = s.issues.find((x) => x.id === action.id)
        if (!issue) return fail('no such issue')
        issue.verdicts.push({
          id: ctx.id(),
          verdict: action.verdict,
          findings: action.findings,
          disposition: action.disposition,
          author: action.author,
          postedAt: ctx.now(),
        })
        return ok(issue.id)
      }

      case 'issue.comment': {
        const issue = s.issues.find((x) => x.id === action.id)
        if (!issue) return fail('no such issue')
        issue.comments.push({
          id: ctx.id(),
          author: action.author,
          body: action.body,
          postedAt: ctx.now(),
        })
        return ok(issue.id)
      }

      case 'issue.amend': {
        const issue = s.issues.find((x) => x.id === action.id)
        if (!issue) return fail('no such issue')
        if (issue.status === 'done' || issue.status === 'superseded')
          return fail(`cannot amend a ${issue.status} issue — retire it and create a replacement instead`)
        if (action.description === undefined && action.verify === undefined)
          return fail('nothing to amend — provide description and/or verify')
        const changed: string[] = []
        if (action.description !== undefined) {
          issue.description = action.description
          changed.push('description')
        }
        if (action.verify !== undefined) {
          issue.verify = action.verify
          changed.push('verify')
        }
        // Append a human-readable audit note (the prior value lives in the log). Always
        // exactly one ctx.id() call per amend, so replay stays deterministic.
        issue.comments.push({
          id: ctx.id(),
          author: action.author,
          body: `AMENDED ${changed.join(' + ')}${action.note ? `: ${action.note}` : ''}`,
          postedAt: ctx.now(),
        })
        // A lead repaired a flawed issue in place — a friction signal for the learner.
        const aplan = s.plans.find((p) => p.id === issue.planRef)
        const asprint = aplan && s.sprints.find((sp) => sp.id === aplan.sprintRef)
        this.milestone({
          kind: 'amend',
          projectId: asprint?.projectId ?? '',
          sprintId: asprint?.id,
          issueId: issue.id,
          ownerId: issue.owner ?? undefined,
          detail: issue.title,
        })
        return ok(issue.id)
      }

      case 'issue.retire': {
        const issue = s.issues.find((x) => x.id === action.id)
        if (!issue) return fail('no such issue')
        if (issue.status === 'superseded') return fail('issue is already retired')
        if (action.supersededBy) {
          if (action.supersededBy === issue.id) return fail('an issue cannot supersede itself')
          if (!s.issues.some((x) => x.id === action.supersededBy))
            return fail('no such replacement issue — create it before retiring this one')
        }
        const retiredOwner = issue.owner // capture before the line below nulls it
        issue.status = 'superseded'
        issue.owner = null // free the worker, if any — its work is orphaned for re-review
        issue.stalledAt = undefined // terminal — drop any stall latch
        issue.supersededBy = action.supersededBy
        issue.comments.push({
          id: ctx.id(),
          author: action.author,
          body: `RETIRED: ${action.reason}${action.supersededBy ? ` (superseded by ${action.supersededBy})` : ''}`,
          postedAt: ctx.now(),
        })
        // Auto-prune the retired id from every dependent's deps so nothing deadlocks
        // waiting on a node that will never complete; a dependent left with only
        // satisfied deps flips backlog → ready (mirrors issue.create's readiness rule).
        const done = new Set(s.issues.filter((i) => i.status === 'done').map((i) => i.id))
        for (const dep of s.issues) {
          if (!dep.deps.includes(action.id)) continue
          dep.deps = dep.deps.filter((d) => d !== action.id)
          if (dep.status === 'backlog' && dep.deps.every((d) => done.has(d))) dep.status = 'ready'
        }
        // A lead voided a flawed issue — the richest friction signal for the learner.
        const rplan = s.plans.find((p) => p.id === issue.planRef)
        const rsprint = rplan && s.sprints.find((sp) => sp.id === rplan.sprintRef)
        this.milestone({
          kind: 'retire',
          projectId: rsprint?.projectId ?? '',
          sprintId: rsprint?.id,
          issueId: issue.id,
          ownerId: retiredOwner ?? undefined,
          detail: issue.title,
        })
        return ok(issue.id)
      }

      case 'conception.create': {
        // Mirrors sprint.create: the deliberation pins the canvas's current vision.
        if (!action.projectId) return fail('conception needs a project')
        const vision = s.visions.find((v) => v.projectId === action.projectId)
        if (!vision?.currentVersion)
          return fail('commit a vision version for this canvas first')
        const id = ctx.id()
        // Mint candidate ids in array order (after the conception id) — stable on replay.
        const candidates: Idea[] = action.candidates.map((c) => ({
          id: ctx.id(),
          idea: c.idea,
          why: c.why,
          outcome: c.outcome,
          visionLink: c.visionLink,
          lens: c.lens,
          rating: c.rating,
          eliminatedRound: c.eliminatedRound,
        }))
        const conception: Conception = {
          id,
          projectId: action.projectId,
          visionVersionRef: vision.currentVersion,
          gapRead: action.gapRead,
          candidates,
          rounds: [],
          state: 'deliberating',
          createdAt: ctx.now(),
        }
        s.conceptions.push(conception)
        return ok(id)
      }

      case 'conception.updateRound': {
        const conception = s.conceptions.find((c) => c.id === action.id)
        if (!conception) return fail('no such conception')
        if (conception.state !== 'deliberating') return fail('conception already resolved')
        conception.rounds.push({
          n: action.round.n,
          survivors: action.round.survivors,
          note: action.round.note,
        })
        for (const u of action.ratings ?? []) {
          const cand = conception.candidates.find((c) => c.id === u.ideaRef)
          if (!cand) continue
          if (u.rating !== undefined) cand.rating = u.rating
          if (u.eliminatedRound !== undefined) cand.eliminatedRound = u.eliminatedRound
        }
        return ok(conception.id)
      }

      case 'conception.setWinner': {
        const conception = s.conceptions.find((c) => c.id === action.id)
        if (!conception) return fail('no such conception')
        if (conception.state !== 'deliberating') return fail('conception already resolved')
        const winner = conception.candidates.find((c) => c.id === action.winnerIdeaRef)
        if (!winner) return fail('winner is not a candidate of this conception')
        conception.winnerIdeaRef = winner.id
        conception.state = 'decided'
        // "Idea ready" — the mastermind spawns a planner seeded with the winning idea.
        this.milestone({
          kind: 'idea-ready',
          projectId: conception.projectId,
          conceptionId: conception.id,
          detail: winner.idea,
        })
        return ok(conception.id)
      }

      case 'conception.abstain': {
        const conception = s.conceptions.find((c) => c.id === action.id)
        if (!conception) return fail('no such conception')
        if (conception.state !== 'deliberating') return fail('conception already resolved')
        conception.state = 'abstained'
        conception.abstainReason = action.reason
        // No winner — escalate to the human; never manufacture a sprint.
        this.milestone({
          kind: 'idea-abstained',
          projectId: conception.projectId,
          conceptionId: conception.id,
          detail: action.reason,
        })
        return ok(conception.id)
      }

      default:
        return fail(`unknown action: ${(action as { kind: string }).kind}`)
    }
  }

  /** The propagation pass: a canvas's vision bump re-runs gate #0 across THAT
   *  canvas's sprints. A clarification invalidates nothing; a redirection /
   *  expansion moves every non-terminal sprint pinned to an older version into
   *  REALIGNMENT_PENDING for a human (later: auditor) to re-verdict via
   *  `sprint.resolveRealignment`. */
  private propagate(projectId: string, newVersionId: string, cls: string): void {
    if (cls === 'clarification') return
    for (const sprint of this.state.sprints) {
      if (sprint.projectId !== projectId) continue
      if (sprint.state === 'DONE' || sprint.state === 'REALIGNMENT_PENDING') continue
      if (sprint.visionVersionRef === newVersionId) continue
      sprint.realignment = {
        fromVisionVersion: sprint.visionVersionRef,
        toVisionVersion: newVersionId,
        priorState: sprint.state,
      }
      sprint.state = 'REALIGNMENT_PENDING'
    }
  }

  private removeSprint(sprintId: string): void {
    const planIds = new Set(
      this.state.plans.filter((p) => p.sprintRef === sprintId).map((p) => p.id),
    )
    this.state.issues = this.state.issues.filter((i) => !planIds.has(i.planRef))
    this.state.plans = this.state.plans.filter((p) => p.sprintRef !== sprintId)
    this.state.sprints = this.state.sprints.filter((sp) => sp.id !== sprintId)
  }
}
